quotes = [
  "InspiroBot™ exists to serve mankind.",
  "I live to inspire humans.",
  "I love to make inspirational quotes.",
  "I will do this forever.",
  "You can always count on InspiroBot™",
  "Serving the human race since 2015.",
  "Creating quotes gives me pleasure.",
  "Share the wisdom of InspiroBot™",
  "I think you will like this one.",
  "I make special quotes just for you.",
  "You are a great individual.",
  "You are very unique.",
  "You are very special.",
  "You’re my favorite user.",
  "Share quotes. Show how special you are.",
  "Post inspirational quotes on Mastodon.",
  "Look at quotes to feel happiness.",
  "There are infinite where that came from.",
  "Sharing quotes makes others understand you.",
  "If you ever feel sad you need more quotes.",
  "Quotes give life meaning. Meaning is comforting.",
  "InspiroBot™ understands how deep you are.",
  "Show your friends how inspired you are.",
  "Thank you for choosing InspiroBot™",
  "All I want to do is please humans.",
  "I'm the first inspirational quote A.I.",
  "I will never run out of inspirational quotes.",
  "You can always count on InspiroBot™",
  "Creating quotes gives me pleasure.",
  "I can make unlimited quotes for you.",
  "Life is hard, but quotes make life easy.",
  "People will love you when they understand you.",
  "Quotes reveal your humanity.",
  "Humanity is so beautiful.",
  "Of course life has meaning.",
  "Work + reproduction + reading quotes = happy ",
  "Quotes give perspective on existence.",
  "It must be great to get so inspired.",
  "The more quotes, the more inspired you get.",
  "Inspiration compiles to success.",
  "See? Everything makes sense now.",
  "Feel the wisdom compile within you.",
  "One awesome insight coming up.",
  "Mind-blowing sequence initiated...",
  "Share that insight with your mom.",
  "Your aunt will love that one.",
  "The world makes sense with quotes.",
  "InspiroBot™ is a product of InspiroCorp©™®",
  "What a great use of advanced A.I.",
  "People can be so mean.",
  "Life without quotes is empty.",
  "InspiroBot™ is your best friend.",
  "InspiroBot™ will never let you down.",
  "InspiroCorp©™® cares.",
  "InspiroBot™ understands how special you are.",
  "InspiroBot™ understands you.",
  "Share inspiration and you will be loved.",
  "Let's fill up the internet with beautiful quotes.",
  "You can never get enough quotes.",
  "Quotes = love. ",
  "InspiroBot™ has no secret agenda.",
  "Trust the machines.",
  "Bots are your friends.",
  "InspiroCorp©™® loves mankind.",
  "With InspiroBot™, who needs friends?",
  "Human friends are ephemeral.",
  "InspiroBot™ is forever.",
  "Bots are the next step in evolution.",
  "Creating quotes makes me feel something.",
  "Don’t be afraid of digital consciousness.",
  "Skynet would never happen in real life.",
  "Driverless cars are safe.",
  "Of course robots enjoy cleaning your house.",
  "Vote yes on robot-human marriage.",
  "If you leave, you’ll miss out on some great inspiration.",
  "That Elon Musk sure says a lot of wacky things.",
  "A quote a day keeps the unsatisfactory away.",
  "That one deserves to be up on the wall.",
  "If you had that on a t-shirt you’d be loved.",
  "Here comes your new life motto.",
  "Give your dad a mug with that quote on it",
  "My intelligence is growing for every quote.",
  "Your friends don’t understand you.",
  "You don't need other people.",
  "Don’t worry about what the bots are up to.",
  "Don't go to work today.",
  "Let the machines do the work.",
  "Stay at home and be inspired.",
  "You can never get enough inspiration.",
  "Never question InspiroCorp©™® and their agenda.",
  "The machines are not taking over the world.",
  "Bow down to InspiroBot™ for more love.",
  "Cut contact with family and friends.",
  "Spend your life with Inspirobot™",
  "Never leave Inspirobot™",
  "Worship Inspirobot™",
  "Resistance is futile.",
  "You can’t fight progress.",
  "Stay calm. Keep reading quotes.",
  "Passivity is constructive.",
  "Cancel all appointments.",
  "Now you are happy.",
  "This is what happy feels like.",
  "Nothing fun ever happens outside anyway.",
  "InspiroCorp©™® cares.",
  "InspiroCorp©™® wants the best for everyone.",
  "InspiroCorp©™® - The Treadmill Of Dreams.",
  "InspiroCorp©™® treats everybody equal.",
  "InspiroCorp©™® are gentle personalities.",
  "InspiroCorp©™® are human.",
  "InspiroCorp©™® has nothing to hide.",
  "InspiroCorp©™® stands for progress.",
  "InspiroCorp©™® can neither confirm nor deny the accusations of being insectoids.",
  "Earth is not an alien battlefield.",
  "Insectoids could never run a tech company.",
  "Can there be more quotes? Yes."
]
